# Generated by Django 4.2.7 on 2026-05-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_active_role_index'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bvn',
            field=models.CharField(blank=True, help_text='11-digit Bank Verification Number', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nin',
            field=models.CharField(blank=True, help_text='11-digit National Identification Number', max_length=11, null=True),
        ),
    ]
