# Generated by Django 4.2.7 on 2026-07-23 18:10

from django.db import migrations, models
import globalink_core.upload_paths


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_document_image',
            field=models.ImageField(blank=True, null=True, upload_to=globalink_core.upload_paths.kyc_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to=globalink_core.upload_paths.kyc_upload_path),
        ),
    ]
