# Generated by Django 5.2.8 on 2026-02-05 08:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_wallet_account_number_wallet_account_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit (Top-up)'), ('payment', 'Payment for Order/Job'), ('escrow_lock', 'Locked in Escrow'), ('escrow_release', 'Released from Escrow'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal to Bank'), ('fee', 'Platform Fee'), ('bill_payment', 'VTpass Bill Payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='account_reference',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
