# Generated by Django 5.2.8 on 2026-03-18 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='finance.wallet'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
