# Generated by Django 4.2.7 on 2026-05-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaction_transaction_type_and_more'),
        ('finance', '0004_add_pending_balance_to_wallet'),
    ]

    operations = [
    ]
