# Generated by Django 4.2.7 on 2026-06-08 00:20

from decimal import Decimal
from django.db import migrations, models


def seed_default_markups(apps, schema_editor):
    DataMarkup = apps.get_model('finance', 'DataMarkup')
    defaults = [
        ('mtn-data', 'MTN', Decimal('50.00')),
        ('glo-data', 'Glo', Decimal('50.00')),
        ('airtel-data', 'Airtel', Decimal('50.00')),
        ('9mobile-data', '9mobile', Decimal('50.00')),
    ]
    for network, label, amount in defaults:
        DataMarkup.objects.get_or_create(
            network=network,
            defaults={
                'network_label': label,
                'markup_amount': amount,
                'is_active': True,
            }
        )


def reverse_seed(apps, schema_editor):
    DataMarkup = apps.get_model('finance', 'DataMarkup')
    DataMarkup.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_merge_rename_and_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMarkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(help_text='e.g. mtn-data, glo-data, airtel-data, 9mobile-data', max_length=50, unique=True)),
                ('network_label', models.CharField(help_text='Display name e.g. MTN, Glo', max_length=50)),
                ('markup_amount', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Fixed markup amount added to the original price (₦)', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Markup',
                'verbose_name_plural': 'Data Markups',
            },
        ),
        migrations.RunPython(seed_default_markups, reverse_seed),
    ]
