# Generated by Django 4.2.7 on 2026-06-08 00:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_datamarkup'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamarkup',
            name='price_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.10'), help_text='Multiplier on Nellobyte price (e.g. 1.10 = sell at 110% of original)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='datamarkup',
            name='markup_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Fixed markup amount added to the original price (₦) — legacy, use price_factor instead', max_digits=10),
        ),
    ]
