# Generated by Django 4.2.7 on 2026-06-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_datamarkup_price_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(help_text='e.g. mtn-data, glo-data', max_length=50)),
                ('variation_code', models.CharField(help_text='Plan ID from Nellobyte', max_length=100)),
                ('plan_name', models.CharField(blank=True, max_length=255)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Custom selling price for this plan. Leave blank to use price_factor.', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Plan Price Override',
                'verbose_name_plural': 'Data Plan Price Overrides',
                'unique_together': {('network', 'variation_code')},
            },
        ),
    ]
