# Generated by Django 4.2.7 on 2026-07-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_dataplanprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit (Top-up)'), ('payment', 'Payment for Order/Job'), ('escrow_lock', 'Locked in Escrow'), ('escrow_release', 'Released from Escrow'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal to Bank'), ('fee', 'Platform Fee'), ('bill_payment', 'VTpass Bill Payment'), ('promotion', 'Promoted Post Fee')], max_length=20),
        ),
    ]
