# Generated by Django 5.2.8 on 2026-01-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
