# Generated by Django 5.2.8 on 2026-01-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
