# Generated by Django 5.2.8 on 2026-01-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_store_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_ad',
            field=models.BooleanField(default=False),
        ),
    ]
