# Generated by Django 5.2.8 on 2026-03-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='monnify_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='monnify_sub_account_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready_for_pickup', 'Ready for Pickup'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
