# Generated by Django 5.2.8 on 2026-05-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_remove_message_conversation_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'price'], name='market_prod_categor_f64697_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='market_prod_created_762148_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', '-created_at'], name='market_prod_shop_id_c95f4a_idx'),
        ),
    ]
