# Generated by Django 5.2.8 on 2026-05-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_alter_product_price_alter_shop_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='business_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='date_applied',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_docs/ids/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='owner_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('drivers_license', "Driver's License"), ('passport', 'Passport')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_docs/logos/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(blank=True, choices=[('retailer', 'Retailer'), ('wholesaler', 'Wholesaler'), ('manufacturer', 'Manufacturer'), ('service_provider', 'Service Provider')], max_length=30, null=True),
        ),
    ]
