# Generated by Django 4.2.7 on 2026-05-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_shop_business_phone_shop_country_shop_date_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid (Settled)'), ('confirmed', 'Confirmed by Buyer'), ('escrow_held', 'Held in Escrow'), ('released', 'Released to Seller'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
