# Generated by Django 4.2.7 on 2026-05-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
