# Generated by Django 4.2.7 on 2026-05-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_alter_product_video_alter_shop_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_ad_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
