# Generated by Django 4.2.7 on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('market', '0014_alter_order_payment_status'),
        ('market', '0015_alter_product_video_alter_shop_logo'),
        ('market', '0016_product_video_ad_url'),
    ]

    dependencies = [
        ('market', '0013_shop_business_phone_shop_country_shop_date_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid (Settled)'), ('confirmed', 'Confirmed by Buyer'), ('escrow_held', 'Held in Escrow'), ('released', 'Released to Seller'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video_ad_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
