# Generated by Django 4.2.7 on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('market', '0013_shop_business_phone_shop_country_shop_date_applied_and_more'),
        ('market', '0014_alter_order_payment_status'),
        ('market', '0015_alter_product_video_alter_shop_logo'),
        ('market', '0016_product_video_ad_url'),
    ]

    dependencies = [
        ('market', '0012_alter_product_price_alter_shop_is_active_and_more'),
    ]

    operations = [
        # 0013 operations
        migrations.AddField(
            model_name='shop',
            name='business_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='date_applied',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_docs/ids/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='owner_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('drivers_license', "Driver's License"), ('passport', 'Passport')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_docs/logos/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(blank=True, choices=[('retailer', 'Retailer'), ('wholesaler', 'Wholesaler'), ('manufacturer', 'Manufacturer'), ('service_provider', 'Service Provider')], max_length=30, null=True),
        ),
        # 0014 operations
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid (Settled)'), ('confirmed', 'Confirmed by Buyer'), ('escrow_held', 'Held in Escrow'), ('released', 'Released to Seller'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        # 0015 operations
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        # 0016 operations
        migrations.AddField(
            model_name='product',
            name='video_ad_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
