# Generated by Django 4.2.7 on 2026-06-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rider',
        ),
    ]
