# Generated by Django 5.2.8 on 2026-06-11 01:00

from django.db import migrations


def backfill_order_numbers(apps, schema_editor):
    Order = apps.get_model('market', 'Order')
    db_alias = schema_editor.connection.alias

    buyer_ids = Order.objects.using(db_alias).filter(
        order_number__isnull=True
    ).values_list('buyer_id', flat=True).distinct()

    for buyer_id in buyer_ids:
        orders = Order.objects.using(db_alias).filter(
            buyer_id=buyer_id
        ).order_by('created_at', 'id')

        for idx, order in enumerate(orders, start=1):
            order.order_number = idx
            order.save(update_fields=['order_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_order_order_number_alter_order_unique_together'),
    ]

    operations = [
        migrations.RunPython(backfill_order_numbers, migrations.RunPython.noop),
    ]
