# Generated by Django 4.2.7 on 2026-07-21 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0020_backfill_order_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.CharField(max_length=300)),
                ('target_link', models.URLField()),
                ('duration_type', models.CharField(choices=[('24h', '24 Hours'), ('3days', '3 Days'), ('1wk', '1 Week')], max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
