# Generated by Django 4.2.7 on 2026-07-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_promotedpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotedPostPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_type', models.CharField(choices=[('24h', '24 Hours'), ('3days', '3 Days'), ('1wk', '1 Week')], max_length=10, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to fall back to the default price')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promoted Post Pricing',
                'verbose_name_plural': 'Promoted Post Pricing',
            },
        ),
    ]
