# Generated by Django 4.2.7 on 2026-07-23 18:10

from django.db import migrations, models
import globalink_core.upload_paths


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_promotedpost_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='id_document_image',
            field=models.ImageField(blank=True, null=True, upload_to=globalink_core.upload_paths.kyc_upload_path),
        ),
        migrations.AlterField(
            model_name='shop',
            name='id_document',
            field=models.ImageField(blank=True, null=True, upload_to=globalink_core.upload_paths.kyc_upload_path),
        ),
        migrations.AlterField(
            model_name='shop',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to=globalink_core.upload_paths.kyc_upload_path),
        ),
    ]
