# Generated by Django 5.2.8 on 2026-07-31 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0025_alter_merchantprofile_id_document_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promotedpost',
            name='contact_preference',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp Only'), ('phone', 'Phone Call Only'), ('both', 'WhatsApp + Phone Call'), ('chat', 'In-app Chat')], default='chat', max_length=10),
        ),
        migrations.AddField(
            model_name='promotedpost',
            name='promotion_type',
            field=models.CharField(choices=[('product', 'Existing Product'), ('standalone', 'Sell an Item')], default='product', max_length=12),
        ),
        migrations.AlterField(
            model_name='promotedpost',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promoted_posts', to='market.product'),
        ),
        migrations.CreateModel(
            name='StandaloneAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_ads', to='market.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='promotedpost',
            name='standalone_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promoted_posts', to='market.standalonead'),
        ),
        migrations.CreateModel(
            name='StandaloneAdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('is_primary', models.BooleanField(default=False)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.standalonead')),
            ],
        ),
    ]
