# Generated by Django 4.2.7 on 2026-09-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0027_promotedpost_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
